-- Snapshot of ALM_ZAIN_KSA.combinedPurchaseOrderView as it exists LIVE in the database.
-- Captured: 2026-09-21
-- This capture reflects a real fix applied to the live view on this date (see below),
-- not just a baseline reference like the 2026-09-17 snapshot.
-- This file is a snapshot for reference only; it is not executed by the application.
-- The view itself lives in the database and must be applied there directly.
--
-- Fix applied 2026-09-21: the previous view fanned out badly on two unconstrained joins,
-- returning up to ~40x too many rows per PO and taking 90+ seconds for a single PO's
-- worth of data (confirmed: PO 23759 went from 3,807 rows / ~94s to 295 rows / ~a few
-- seconds after this fix). This broke /createAcceptanceRequest's bulk-upload serial-number
-- validation, which was silently falling back to the wrong (PO-line-level) serialized flag
-- once its PO/UPL data fetch stalled on the slow query.
--   1. The tb_PurchaseOrderUPL join had no status filter, so every revision of a UPL line
--      (ACTIVE, DELETED, PENDING - this table keeps superseded revisions as rows instead of
--      updating in place) came back as its own duplicate row. Fixed by requiring
--      upl.status = 'ACTIVE' in the join condition.
--   2. The tb_Category join matched only on itemCategoryCode, but that column is not unique
--      there - e.g. code 1000.11090.10 has 5 active rows, one per distinct `scope` value.
--      Fixed by joining through a deduplicated derived table (one row per itemCategoryCode,
--      lowest recordNo wins) instead of tb_Category directly. Note: this is a pragmatic,
--      deterministic tie-break, not a resolution of the underlying tb_Category duplication -
--      that data-quality question (which scope should "win" for a given category code) is
--      still open and belongs to whoever owns that table's data.
--
-- Captured directly from a fresh `SHOW CREATE VIEW` immediately after applying the fix, and
-- verified via a strict, backtick/string-quote-aware tokenizer (not a naive whitespace-strip,
-- which would hide a corrupted identifier) that this formatted version is token-for-token
-- identical to the live definition - see the 2026-09-17 snapshot's own header for why that
-- distinction matters: a prior naive reformatting once silently corrupted a case-sensitive
-- join alias in this same file.

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `combinedPurchaseOrderView` AS select `po`.`recordNo` AS `poRecordNo`,
 `po`.`poNumber` AS `poNumber`,
 `po`.`typeLookUpCode` AS `typeLookUpCode`,
 `po`.`blanketTotalAmount` AS `blanketTotalAmount`,
 `po`.`releaseNum` AS `releaseNum`,
 `po`.`lineNumber` AS `lineNumber`,
 `po`.`prNum` AS `prNum`,
 `po`.`newProjectName` AS `poProjectName`,
 `po`.`newProjectName` AS `newProjectName`,
 `po`.`itemPartNumber` AS `itemPartNumber`,
 `po`.`prSubAllow` AS `prSubAllow`,
 `po`.`countryOfOrigin` AS `poCountryOfOrigin`,
 (case when (`po`.`poQtyNew` > 0) then `po`.`poQtyNew` else `po`.`poOrderQuantity` end) AS `poOrderQuantity`,
 (case when (`upl`.`uplLineQuantity` > 0) then (select coalesce(sum(`dcc`.`deliveredQty`),0) from (`tb_DCC_LN` `dcc` join `tb_DCC` `DCC` on((`dcc`.`dccId` = `DCC`.`recordNo`))) where ((`dcc`.`uplLineNumber` = `upl`.`uplLine`) and (`upl`.`poLineNumber` = `dcc`.`lineNumber`) and (`upl`.`poNumber` = `DCC`.`poNumber`) and (`DCC`.`status` not in ('incomplete','rejected')))) else 0 end) AS `UPLACPTRequestValue`,
 (case when (`upl`.`uplLineQuantity` > 0) then (select (coalesce(sum(`dcc`.`deliveredQty`),0) / nullif(sum((`upl`.`poLineQuantity` * `upl`.`poLineUnitPrice`)),0)) from (`tb_DCC_LN` `dcc` join `tb_DCC` `DCC` on((`dcc`.`dccId` = `DCC`.`recordNo`))) where ((`dcc`.`uplLineNumber` = `upl`.`uplLine`) and (`upl`.`poLineNumber` = `dcc`.`lineNumber`) and (`upl`.`poNumber` = `DCC`.`poNumber`) and (`DCC`.`status` not in ('incomplete','rejected')))) else 0 end) AS `POAcceptanceQty`,
 (select coalesce(sum(`subquery`.`POAcceptanceQty`),0) from (select `uplInner`.`poNumber` AS `poNumber`,`uplInner`.`poLineNumber` AS `poLineNumber`,((`uplInner`.`uplLineQuantity` * `uplInner`.`uplLineUnitPrice`) / nullif((`uplInner`.`poLineQuantity` * `uplInner`.`poLineUnitPrice`),0)) AS `POAcceptanceQty` from `tb_PurchaseOrderUPL` `uplInner` where (`uplInner`.`uplLineQuantity` < 0)) `subquery` where ((`subquery`.`poNumber` = `upl`.`poNumber`) and (`subquery`.`poLineNumber` = `upl`.`poLineNumber`))) AS `POLineAcceptanceQty`,
 (case when (`upl`.`recordNo` is not null) then (case when (`po`.`poQtyNew` > 0) then `po`.`quantityDueNew` else `po`.`quantityDueOld` end) else ((case when (`po`.`poQtyNew` > 0) then `po`.`quantityDueNew` else `po`.`quantityDueOld` end) - (select coalesce(sum(`dcc`.`deliveredQty`),0) from (`tb_DCC_LN` `dcc` join `tb_DCC` `DCC` on((`dcc`.`dccId` = `DCC`.`recordNo`))) where ((`DCC`.`poNumber` = `po`.`poNumber`) and (`dcc`.`lineNumber` = `po`.`lineNumber`) and (`DCC`.`status` not in ('incomplete','rejected','returned'))))) end) AS `poPendingQuantity`,
 `po`.`poQtyNew` AS `poQtyNew`,
 `po`.`quantityReceived` AS `quantityReceived`,
 `po`.`currencyCode` AS `poCurrencyCode`,
 `po`.`unitPriceInPoCurrency` AS `unitPriceInPoCurrency`,
 `po`.`unitPriceInSAR` AS `unitPriceInSAR`,
 `po`.`linePriceInPoCurrency` AS `linePriceInPoCurrency`,
 `po`.`linePriceInSAR` AS `linePriceInSAR`,
 `po`.`amountReceived` AS `amountReceived`,
 `po`.`poLineDescription` AS `poLineDescription`,
 `po`.`organizationName` AS `organizationName`,
 `po`.`organizationCode` AS `organizationCode`,
 `po`.`subInventoryCode` AS `subInventoryCode`,
 `po`.`receiptRouting` AS `receiptRouting`,
 `po`.`authorisationStatus` AS `authorisationStatus`,
 `po`.`departmentName` AS `departmentName`,
 `po`.`businessOwner` AS `businessOwner`,
 `po`.`poLineType` AS `poLineType`,
 `po`.`acceptanceType` AS `poAcceptanceType`,
 `po`.`costCenter` AS `costCenter`,
 `po`.`chargeAccount` AS `chargeAccount`,
 `po`.`serialControl` AS `serialControl`,
 `po`.`vendorSerialNumberYN` AS `vendorSerialNumberYN`,
 `po`.`itemType` AS `itemType`,
 `po`.`itemCategoryInventory` AS `itemCategoryInventory`,
 `po`.`inventoryCategoryDescription` AS `inventoryCategoryDescription`,
 `po`.`itemCategoryFA` AS `itemCategoryFA`,
 `po`.`FACategoryDescription` AS `FACategoryDescription`,
 `po`.`itemCategoryPurchasing` AS `itemCategoryPurchasing`,
 `po`.`PurchasingCategoryDescription` AS `PurchasingCategoryDescription`,
 `po`.`vendorName` AS `poVendorName`,
 `po`.`vendorNumber` AS `poVendorNumber`,
 `po`.`approvedDate` AS `poApprovedDate`,
 `po`.`createdDate` AS `poCreatedDate`,
 `po`.`createdBy` AS `poCreatedBy`,
 `po`.`createdByName` AS `poCreatedByName`,
 `upl`.`recordNo` AS `uplRecordNo`,
 `upl`.`manufacturer` AS `uplManufacturer`,
 `upl`.`countryOfOrigin` AS `uplCountryOfOrigin`,
 `upl`.`releaseNumber` AS `uplReleaseNumber`,
 `upl`.`uplLine` AS `uplLine`,
 `upl`.`poLineItemType` AS `uplPoLineItemType`,
 `upl`.`poLineItemCode` AS `uplPoLineItemCode`,
 `upl`.`poLineDescription` AS `uplPoLineDescription`,
 `upl`.`uplLineItemType` AS `uplLineItemType`,
 `upl`.`uplLineItemCode` AS `uplLineItemCode`,
 `upl`.`uplLineDescription` AS `uplLineDescription`,
 `upl`.`zainItemCategoryCode` AS `zainItemCategoryCode`,
 `upl`.`zainItemCategoryDescription` AS `zainItemCategoryDescription`,
 `upl`.`uplItemSerialized` AS `uplItemSerialized`,
 (case when (`upl`.`recordNo` is not null) then `upl`.`activeOrPassive` else `po`.`activeOrPassive` end) AS `activeOrPassive`,
 `upl`.`uom` AS `uplUom`,
 `upl`.`currency` AS `uplCurrency`,
 `upl`.`poLineQuantity` AS `uplPoLineQuantity`,
 `upl`.`poLineUnitPrice` AS `uplPoLineUnitPrice`,
 `upl`.`uplLineQuantity` AS `uplLineQuantity`,
 `upl`.`uplLineUnitPrice` AS `uplLineUnitPrice`,
 `upl`.`substituteItemCode` AS `substituteItemCode`,
 `upl`.`remarks` AS `uplRemarks`,
 `cat`.`scope` AS `scopeOfWork`,
 `upl`.`dptApprover1` AS `dptApprover1`,
 `upl`.`dptApprover2` AS `dptApprover2`,
 `upl`.`dptApprover3` AS `dptApprover3`,
 `upl`.`dptApprover4` AS `dptApprover4`,
 `upl`.`regionalApprover` AS `regionalApprover`,
 `upl`.`createdBy` AS `uplCreatedBy`,
 `upl`.`createdByName` AS `uplCreatedByName`,
 (case when ((`po`.`lineCancelFlag` = 0) and (`po`.`authorisationStatus` = 'APPROVED') and (`po`.`poClosureStatus` = 'OPEN')) then 'YES' else 'NO' end) AS `canRaiseAcceptance`,
 (case when ((`upl`.`uplLineQuantity` - (select coalesce(sum(`dcc`.`deliveredQty`),0) from (`tb_DCC_LN` `dcc` join `tb_DCC` `DCC` on((`dcc`.`dccId` = `DCC`.`recordNo`))) where ((`dcc`.`uplLineNumber` = `upl`.`uplLine`) and (`upl`.`poLineNumber` = `dcc`.`lineNumber`) and (`upl`.`poNumber` = `DCC`.`poNumber`) and (`DCC`.`status` not in ('incomplete','rejected'))))) is not null) then (`upl`.`uplLineQuantity` - (select coalesce(sum(`dcc`.`deliveredQty`),0) from (`tb_DCC_LN` `dcc` join `tb_DCC` `DCC` on((`dcc`.`dccId` = `DCC`.`recordNo`))) where ((`dcc`.`uplLineNumber` = `upl`.`uplLine`) and (`upl`.`poLineNumber` = `dcc`.`lineNumber`) and (`upl`.`poNumber` = `DCC`.`poNumber`) and (`DCC`.`status` not in ('incomplete','rejected','returned'))))) else `upl`.`uplLineQuantity` end) AS `uplPendingQuantity`,
 `cat`.`categoryDescription` AS `categoryDescription` 
from ((`tb_PurchaseOrder` `po` left join `tb_PurchaseOrderUPL` `upl` on(((`po`.`poNumber` = `upl`.`poNumber`) and (`po`.`lineNumber` = `upl`.`poLineNumber`) and (`upl`.`status` = 'ACTIVE')))) left join (select `c`.`recordNo` AS `recordNo`,`c`.`recordDateTime` AS `recordDateTime`,`c`.`itemCategoryCode` AS `itemCategoryCode`,`c`.`categoryDescription` AS `categoryDescription`,`c`.`scope` AS `scope`,`c`.`major` AS `major`,`c`.`majorCode` AS `majorCode`,`c`.`minor` AS `minor`,`c`.`minorCode` AS `minorCode`,`c`.`sub` AS `sub`,`c`.`subCode` AS `subCode`,`c`.`SOW` AS `SOW`,`c`.`usefulLife` AS `usefulLife`,`c`.`attributes` AS `attributes`,`c`.`amuComments` AS `amuComments`,`c`.`budgetingCategoryMapping` AS `budgetingCategoryMapping`,`c`.`groupCategoryMapping` AS `groupCategoryMapping`,`c`.`createdBy` AS `createdBy`,`c`.`updatedBy` AS `updatedBy`,`c`.`updatedDateTime` AS `updatedDateTime`,`c`.`status` AS `status`,`c`.`rn` AS `rn` from (select `c1`.`recordNo` AS `recordNo`,`c1`.`recordDateTime` AS `recordDateTime`,`c1`.`itemCategoryCode` AS `itemCategoryCode`,`c1`.`categoryDescription` AS `categoryDescription`,`c1`.`scope` AS `scope`,`c1`.`major` AS `major`,`c1`.`majorCode` AS `majorCode`,`c1`.`minor` AS `minor`,`c1`.`minorCode` AS `minorCode`,`c1`.`sub` AS `sub`,`c1`.`subCode` AS `subCode`,`c1`.`SOW` AS `SOW`,`c1`.`usefulLife` AS `usefulLife`,`c1`.`attributes` AS `attributes`,`c1`.`amuComments` AS `amuComments`,`c1`.`budgetingCategoryMapping` AS `budgetingCategoryMapping`,`c1`.`groupCategoryMapping` AS `groupCategoryMapping`,`c1`.`createdBy` AS `createdBy`,`c1`.`updatedBy` AS `updatedBy`,`c1`.`updatedDateTime` AS `updatedDateTime`,`c1`.`status` AS `status`,row_number() OVER (PARTITION BY `c1`.`itemCategoryCode` ORDER BY `c1`.`recordNo` )  AS `rn` from `tb_Category` `c1` where (`c1`.`status` = 1)) `c` where (`c`.`rn` = 1)) `cat` on(((case when (`upl`.`recordNo` is not null) then `upl`.`zainItemCategoryCode` else `po`.`itemCategoryInventory` end) = `cat`.`itemCategoryCode`))) 
group by `po`.`recordNo`,
 `po`.`poNumber`,
 `po`.`typeLookUpCode`,
 `po`.`blanketTotalAmount`,
 `po`.`releaseNum`,
 `po`.`lineNumber`,
 `po`.`prNum`,
 `po`.`newProjectName`,
 `po`.`itemPartNumber`,
 `po`.`prSubAllow`,
 `po`.`countryOfOrigin`,
 `po`.`poQtyNew`,
 `po`.`quantityReceived`,
 `po`.`currencyCode`,
 `po`.`unitPriceInPoCurrency`,
 `po`.`unitPriceInSAR`,
 `po`.`linePriceInPoCurrency`,
 `po`.`linePriceInSAR`,
 `po`.`amountReceived`,
 `po`.`poLineDescription`,
 `po`.`organizationName`,
 `po`.`organizationCode`,
 `po`.`subInventoryCode`,
 `po`.`receiptRouting`,
 `po`.`authorisationStatus`,
 `po`.`departmentName`,
 `po`.`businessOwner`,
 `po`.`poLineType`,
 `po`.`acceptanceType`,
 `po`.`costCenter`,
 `po`.`chargeAccount`,
 `po`.`serialControl`,
 `po`.`vendorSerialNumberYN`,
 `po`.`itemType`,
 `po`.`itemCategoryInventory`,
 `po`.`inventoryCategoryDescription`,
 `po`.`itemCategoryFA`,
 `po`.`FACategoryDescription`,
 `po`.`itemCategoryPurchasing`,
 `po`.`PurchasingCategoryDescription`,
 `po`.`vendorName`,
 `po`.`vendorNumber`,
 `po`.`approvedDate`,
 `po`.`createdDate`,
 `po`.`createdBy`,
 `po`.`createdByName`,
 `po`.`activeOrPassive`,
 `upl`.`recordNo`,
 `upl`.`manufacturer`,
 `upl`.`countryOfOrigin`,
 `upl`.`releaseNumber`,
 `upl`.`uplLine`,
 `upl`.`poLineItemType`,
 `upl`.`poLineItemCode`,
 `upl`.`poLineDescription`,
 `upl`.`uplLineItemType`,
 `upl`.`uplLineItemCode`,
 `upl`.`uplLineDescription`,
 `upl`.`zainItemCategoryCode`,
 `upl`.`zainItemCategoryDescription`,
 `upl`.`uplItemSerialized`,
 `upl`.`activeOrPassive`,
 `upl`.`uom`,
 `upl`.`currency`,
 `upl`.`poLineQuantity`,
 `upl`.`poLineUnitPrice`,
 `upl`.`uplLineQuantity`,
 `upl`.`uplLineUnitPrice`,
 `upl`.`substituteItemCode`,
 `upl`.`remarks`,
 `cat`.`scope`,
 `upl`.`dptApprover1`,
 `upl`.`dptApprover2`,
 `upl`.`dptApprover3`,
 `upl`.`dptApprover4`,
 `upl`.`regionalApprover`,
 `upl`.`createdBy`,
 `upl`.`createdByName`,
 `cat`.`categoryDescription`;
